name: Run Unit Tests

on:
  workflow_dispatch: # Allows you to trigger the test manually from the GitHub UI
  push:
    # Added 'Hash-MT' so it runs automatically when you push to this branch
    branches: [ "main", "Refactoring", "feature/bulk-actions", "feature/drag-drop", "Hash-MT"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests with Pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest -v tests/
